name: Check
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
      - .gitignore
      - .gitattributes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Clone the repo
        uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: make sync
      - name: Check formatting
        run: make check-format
      - name: Lint
        run: make check-lint
      - name: Check types
        run: make check-types
      - name: Run tests
        run: make test
